#upgrade to node-18
FROM node:18.14.2 as dependencies
WORKDIR /app
COPY package.json ./ package-lock.json ./
RUN npm install -g npm@9.6.3
RUN npm --verbose install --force

FROM node:18.14.2 as builder
WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN npm run build --verbose

FROM node:18.14.2 as runner
WORKDIR /app

# If you are using a custom next.config.js file, uncomment this line.
COPY --from=builder /app/build ./build
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

ENV NODE_ENV production
ENV PORT 5600
ENV NEXT_TELEMETRY_DISABLED 1
EXPOSE 5600

# SERVE react build
RUN npm install -g serve
CMD ["serve", "-s", "build"]